run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "cmd/*"
      linters:
        - lll
        - goconst
    - path: "cmd/exp/*"
      linters:
        - dupl
        - goconst
        - gocyclo
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - gci
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  revive:
    rules:
      - name: comment-spacings

  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/lxc/cluster-api-provider-incus

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/lxc/cluster-api-provider-incus)
      - dot
