name: Build Kubeadm Images

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Kubernetes version, e.g. "v1.33.0"
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        # amd64 images
        - { infrastructure: incus,  type: container,        arch: amd64 }
        - { infrastructure: incus,  type: virtual-machine,  arch: amd64 }
        - { infrastructure: lxd,    type: virtual-machine,  arch: amd64 }

        # arm64 images
        - { infrastructure: incus,  type: container,        arch: arm64 }
        # - { infrastructure: incus,  type: virtual-machine,  arch: arm64 }    # arm64 runners do not support kvm
        # - { infrastructure: lxd,    type: virtual-machine,  arch: arm64 }    # arm64 runners do not support kvm
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup infrastructure
        run: |
          ./hack/scripts/ci/setup-${{ matrix.infrastructure }}.sh

      - name: Build image
        run: |
          go run ./cmd/exp/image-builder kubeadm --v=4 --kubernetes-version=${{ inputs.version }} --instance-type=${{ matrix.type }} --output=image.tar.gz

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: kubeadm-${{ inputs.version }}-${{ matrix.infrastructure }}-${{ matrix.type }}-${{ matrix.arch }}
          path: image.tar.gz
